#!/usr/bin/env python3
"""Consistency sweep for the FishBot manuscripts.

Run from anywhere:

    python3 paper/check.py            # every manuscript present (v0.4 and v0.5)
    python3 paper/check.py --v04      # the v0.4 manuscript only
    python3 paper/check.py --v05      # the v0.5 manuscript only

Three classes of check, all of which have caught real defects in these papers:

  1. BANNED  -- phrases the review of that version ruled out.  For v0.4, e.g.
     calling the declaration rule "optimal", calling the two-ply refinement
     "exact", or asserting an upper bound on exploitability.  For v0.5, e.g.
     calling the deadlock an information freeze, calling an allocation
     probability computed on the deployed approximate belief "exact", or
     asserting an upper bound on exploitability.
  2. MACROS  -- every \\num... macro referenced by a section must be defined in
     that manuscript's numbers file (generated by engine/build_tables.py, with a
     hand-written \\providecommand placeholder until the generator covers it),
     and macros that already carry a percent sign must not be followed by
     another.
  3. STRUCTURE -- every \\ref/\\eqref resolves, every \\cite resolves, every
     \\input names a file that exists, and no table or figure lacks a caption or
     a label.

Exit status is non-zero if anything in class 1 or 2 fires in any manuscript, or
if class 3 finds a dangling reference.
"""
import os
import re
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------- 1. banned
# (pattern, why).  Patterns are case-insensitive regexes matched against the
# LaTeX source with comments stripped.
BANNED_V04 = [
    (r'optimal[- ]stopping',            'the declaration rule is a value-based stopping rule, not an optimal-stopping solution'),
    (r'optimal stopping',               'same'),
    (r'\bexact two-ply\b',              'the two-ply branches are recomputed with the Sinkhorn approximation'),
    (r'two-ply.{0,40}\bexact\b',        'the two-ply branches are approximate'),
    (r'rules-exact',                    'say "exact for the specified rules dialect"'),
    (r'\bthe real rules\b',             'say "the rules dialect studied"'),
    (r'exact public[- ]belief',         'the posterior is observer-conditioned, not a common public belief'),
    (r'public belief state game',       'same'),
    (r'\bno previous (agent|work|engine)\b', 'use "we found no prior published work that ..."'),
    (r'\bthe first (Fish|agent|engine)\b',   'use "we found no prior published work that ..."'),
    (r'never been stated',              'use "we found no prior published work that ..."'),
    (r'upper bound.{0,40}exploitab',    'an achieved exploiter score is a lower bound within the search class'),
    (r'exploitab.{0,40}upper bound',    'same'),
    (r'prior .{0,20}adds nothing',      'removing the policy prior cost 3.88 points in the frozen-policy ablation'),
    (r'adds nothing once',              'same'),
    (r'rejection-free(?!.{0,80}C1)',    'rejection-free for C1-C4 only; C5 uses exact rejection'),
    (r'(safe|lossless) pre-?gate',      'the pre-gate has a measured non-zero false-negative rate (E16)'),
    (r'pre-?gate is (safe|lossless)',   'same'),
    (r'the honest (statement|summary|answer)', 'write the precise sentence instead'),
    (r'worth stating precisely',        'write the precise sentence instead'),
    (r'twenty times',                   'the Fast/Block throughput ratio is about 14x'),
    (r'31 (tuned |fitted )?(co-?ordinates|parameters)', 'the fitted vector has 34 coordinates'),
    (r'\$8 ?\\times ?8\$ policy',       'fish verify runs the 9x9 cross-product'),
    (r'four bounded claims',            'the contributions are a paragraph, not a numbered claim list'),
    (r'held-out opponents',             'deals were held out; most opponent identities were not'),
    (r'against \\emph\{every\} policy', 'scope the result to the tested panel'),
    (r'at least \\numWorstCase',        'scope the result to the tested panel'),
    (r'single most valuable',           'say "largest frozen-policy ablation decrease"'),
    (r'exactness makes.{0,30}worse',    'a Block belief substituted into a Fast-fitted policy scored lower'),
    (r'no more information can change', 'ownership may be fixed while allocation information still changes'),
    (r'validated against brute force(?!.{0,200}oracle)', 'cite the oracle experiment (E15) and its coverage'),
    (r'validated against exhaustive enumeration(?!.{0,140}(small|reachable|coverage))',
     'the oracle validates small reachable states only; say so'),
    (r'exhaustive enumeration(?!.{0,160}(small|reachable|skipped|coverage|partial))',
     'always scope the oracle to the states it actually enumerated'),
]

# The v0.5 list.  Every entry is a claim the v0.5 diagnosis measured to be false,
# or a scope the v0.5 evidence does not support.
BANNED_V05 = [
    # -- the deadlock is not an information freeze (P1, P1-verify-*) ----------
    (r'freezes? information',           'ownership monotonicity does not imply informational monotonicity (P1)'),
    (r'informationally frozen',         'same -- 68.5% of legal asks inside a locked half-suit strictly raise a teammate pAlloc'),
    (r'information (?:is|was) frozen',  'same'),
    (r'no (?:more|further) information.{0,60}(arrive|change|available)',
     'asks inside a locked half-suit stay legal and keep publishing certificates (P1 section 2)'),
    (r'(?:the )?deadlock is (?:an? )?(?:information|informational) freeze',
     'the deadlock is a two-question ask-policy cycle (P1 section 1)'),
    (r'frozen half-suit.{0,60}deadlock', 'only 13.0% of dead-run asks sit in a locked half-suit (P1-verify census)'),
    (r'deadlock.{0,60}Theorem~?\\?ref',  'Theorem 1 is not the mechanism in 66% of long games (P1-verify census)'),
    # -- the Fast path is approximate; do not call its output exact -----------
    (r'exact.{0,40}(allocation probability|allocation estimate|joint estimator)',
     'the deployed allocation score runs on the approximate belief; feasibility is exact, the score is not'),
    (r'(allocation probability|allocation estimate|joint estimator).{0,40}\bexact\b', 'same'),
    (r'exact(?:ly)? feasible allocation.{0,40}posterior', 'same'),
    (r'\bexact Bayesian\b',             'the uniform-over-consistent-deals posterior is policy-agnostic, not the true posterior'),
    (r'exact two-ply',                  'the two-ply branches are recomputed with the Sinkhorn approximation'),
    # -- exploitability ------------------------------------------------------
    (r'upper bound.{0,40}exploitab',    'an achieved exploiter score is a lower bound within the search class'),
    (r'exploitab.{0,40}upper bound',    'same'),
    (r'unexploitable',                  'nothing here bounds exploitability'),
    # -- scope of the v0.5 result -------------------------------------------
    (r'v0\.5 (?:is|are) stronger',      'no strength number is reported until the refit lands (sec:results is a stub)'),
    (r'solv\w* the deadlock',           'say what was measured: the dead-run KPIs, on the stated population'),
    (r'(?:the )?pathology is (?:now )?(?:fixed|gone|eliminated)', 'same -- quote the KPI, not the verdict'),
    (r'held-out opponents',             'deals were held out; opponent identities largely were not'),
    (r'\bthe first (Fish|agent|engine)\b', 'use "we found no prior published work that ..."'),
    (r'\bno previous (agent|work|engine)\b', 'same'),
    (r'never been stated',              'same'),
    # -- claims the diagnosis specifically refuted --------------------------
    (r'inference defect',               'switching to the exact belief leaves the longest dead run at 280 (P0)'),
    (r'(?:free|costless) (?:signalling |information )?channel',
     'provable team ownership holds at 0.34% of decisions; the channel must be priced, not gated (P5-verify)'),
    (r'silence channel.{0,40}(works|carries|informative)',
     'priorPhi is card-independent after capacity normalisation and measurably inert (P3)'),
    (r'holding cost.{0,40}(fixes|solves|removes|breaks)',
     'the swept holding cost is a mean-shifter: p90 313->311, longest run 289->289 (DESIGN 0.3)'),
    (r'willingness ladder.{0,40}(works|fires|recovers)(?!.{0,80}M2)',
     'the ladder is inert until the allocator is fixed: statistic exactly 0 in 210/210 pairs (P8)'),
    (r'the v0\.4 paper.{0,60}(freeze|frozen)',
     'the v0.4 PAPER states the correct observation; the error is in E11-termination.md'),
    (r'turn transfer.{0,40}(worth|gain|wins)(?!.{0,60}(zero|nothing|-0))',
     'a ground-truth chooser is worth -0.0007 +/- 0.0024 sets/game (P8)'),
]

# Macros that already contain a percent sign; a following \% is a duplicate.
SELF_PERCENT_V04 = {'numLimitRate', 'numLBRLimit'}
SELF_PERCENT_V05 = {'numVfourLimitRate'}

# Several banned phrases are legitimate inside an explicit disclaimer -- the
# paper is required to say, for instance, that the rule is "not a Bellman-optimal
# stopping value".  A hit is suppressed when a negation cue appears close by.
NEGATION_BASE = (
    r'\b(?:not|never|no longer|rather than|instead of|does not|do not|is not|are not|'
    r'without|nor|neither|cannot|avoid|deny|denies|refrain|but not|other than|'
    r'we make no|makes no|no such|misleading|incorrect|wrong|must not)\b'
)
# The v0.5 manuscript quotes the claims it retracts, so the corrections section
# needs a wider set of cues than a plain negation.
NEGATION_V05_EXTRA = (
    r'|\b(?:false|retract\w*|withdraw\w*|withdrawn|corrected|correction|corrects|'
    r'refut\w*|erroneous|overstate\w*|understate\w*|fails|failed|stale|priced|'
    r'unbuilt|not yet)\b'
)
NEG_WINDOW = 220


class Profile:
    def __init__(self, name, master, sections, numbers, banned, self_percent,
                 negation, extra_dirs):
        self.name = name
        self.master = os.path.join(HERE, master)
        self.sections = os.path.join(HERE, sections)
        self.numbers = os.path.join(HERE, numbers)
        self.banned = banned
        self.self_percent = self_percent
        self.negation = re.compile(negation, re.IGNORECASE)
        self.extra_dirs = [os.path.join(HERE, d) for d in extra_dirs]

    def present(self):
        return os.path.exists(self.master) and os.path.isdir(self.sections)



# ---------------------------------------------------------------- v0.6 -------
# Claims this study measured and refuted, or measured and had to scope.  Each
# entry is a sentence a careless draft of the v0.6 manuscript actually wrote
# before the evidence came in.
BANNED_V06 = list(BANNED_V05) + [
    (r'(?:beats?|wins?).{0,40}every (?:one of the )?(?:five |held-out )?(?:seed )?banks?',
     'FALSE: pooled over every head-to-head cell in the battery v0.6 is 50.53%, 5 of 7 above parity'),
    (r'head to head.{0,40}\b(?:wins?|ahead|stronger|better)\b',
     'v0.6 and v0.5 are NOT separated head to head; say so'),
    (r'(?:ties?|tied candidates?)[^\\]{0,60}irreducible',
     'FALSE: a twelve-deal ensemble separates them (F8-tiesearch.txt); only MARGINAL rules cannot'),
    (r'exchangeable given the information',
     'the measurement establishes equal MARGINALS, not joint exchangeability'),
    (r'policy prior is the (?:only|entire)',
     'FALSE: the approximation still beats the exact law with the prior deleted (F2-belief-noprior.txt)'),
    (r'search[^\\]{0,50}(?:converges to the blueprint|has nothing to add|does not pay)',
     'FALSE: the guarded search takes 52.08% against v0.6 itself over 2,880 games'),
    (r'27 points',
     'the comparable controlled pair is 49.31% against 13.61% = 35.70 points (E12-search.jsonl)'),
    (r'four points\b',
     'the pooled search effect is 2.6 points, not the single best bank'),
    (r'chain.{0,30}(?:pass|re-scoring).{0,40}(?:4\.11|four points|costs? four)',
     'FALSE at two banks: 45.89% and 51.78%, and -0.75 [-2.44, +0.92] paired'),
    (r'uniformly more robust',
     'the minimax-regret gain is carried by the withholder column'),
]
SELF_PERCENT_V06 = set(SELF_PERCENT_V05)
NEGATION_V06_EXTRA = (
    r'|FALSE|refuted|not separated|does not replicate|earlier draft|correction'
)

PROFILES = {
    'v04': Profile('v0.4', 'fishbot_v04.tex', 'sections', 'numbers.tex',
                   BANNED_V04, SELF_PERCENT_V04, NEGATION_BASE,
                   ['tables', 'figures']),
    'v05': Profile('v0.5', 'fishbot_v05.tex', 'sections_v05', 'numbers_v05.tex',
                   BANNED_V05, SELF_PERCENT_V05,
                   NEGATION_BASE + NEGATION_V05_EXTRA,
                   ['tables_v05', 'figures_v05']),
    'v06': Profile('v0.6', 'fishbot_v06.tex', 'sections_v06', 'numbers_v06.tex',
                   BANNED_V06, SELF_PERCENT_V06,
                   NEGATION_BASE + NEGATION_V05_EXTRA + NEGATION_V06_EXTRA,
                   ['tables_v06']),
}


def strip_comments(text):
    out = []
    for line in text.split('\n'):
        i, esc = 0, False
        cut = len(line)
        while i < len(line):
            c = line[i]
            if esc:
                esc = False
            elif c == '\\':
                esc = True
            elif c == '%':
                cut = i
                break
            i += 1
        out.append(line[:cut])
    return '\n'.join(out)


def tex_files(profile):
    """Everything that ships: the sections, the generated tables and figures, and
    the master.  Tables are \\input from sections, so their content reaches the
    reader and has to be swept for banned phrasing and stray Unicode too."""
    files = []
    for d in [profile.sections] + profile.extra_dirs:
        if not os.path.isdir(d):
            continue
        for name in sorted(os.listdir(d)):
            if name.endswith('.tex'):
                files.append(os.path.join(d, name))
    if os.path.exists(profile.master):
        files.append(profile.master)
    return files


def run(profile):
    problems, warnings = [], []

    sources = {}
    for path in tex_files(profile):
        sources[path] = strip_comments(open(path, encoding='utf-8').read())

    rel = lambda p: os.path.relpath(p, HERE)

    # ---- 1. banned phrases -------------------------------------------------
    for path, text in sources.items():
        if rel(path).endswith('bibliography.tex'):
            continue
        for pat, why in profile.banned:
            for m in re.finditer(pat, text, re.IGNORECASE | re.DOTALL):
                lo = max(0, m.start() - NEG_WINDOW)
                hi = min(len(text), m.end() + NEG_WINDOW)
                if profile.negation.search(text[lo:hi]):
                    line = text[:m.start()].count('\n') + 1
                    snippet = ' '.join(m.group(0).split())[:70]
                    warnings.append(f'BANNED? {rel(path)}:{line}  "{snippet}"  '
                                    f'-- appears near a negation; verify it is a disclaimer')
                    continue
                line = text[:m.start()].count('\n') + 1
                snippet = ' '.join(m.group(0).split())[:70]
                problems.append(f'BANNED  {rel(path)}:{line}  "{snippet}"  -- {why}')

    # ---- 2. macros ---------------------------------------------------------
    defined = set()
    if os.path.exists(profile.numbers):
        src = open(profile.numbers, encoding='utf-8').read()
        defined = set(re.findall(r'\\(?:new|provide|renew)command\{\\(num[A-Za-z]+)\}', src))
    else:
        problems.append(f'MACROS  {rel(profile.numbers)} is missing; run engine/build_tables.py')

    used = defaultdict(list)
    for path, text in sources.items():
        for m in re.finditer(r'\\(num[A-Za-z]+)', text):
            used[m.group(1)].append((rel(path), text[:m.start()].count('\n') + 1))
    for name, sites in sorted(used.items()):
        if name not in defined:
            where = ', '.join(f'{f}:{l}' for f, l in sites[:3])
            problems.append(f'MACROS  \\{name} is used ({where}) but not defined in {rel(profile.numbers)}')

    for path, text in sources.items():
        for name in profile.self_percent:
            for m in re.finditer(r'\\' + name + r'(?![A-Za-z])\s*\\%', text):
                line = text[:m.start()].count('\n') + 1
                problems.append(f'MACROS  {rel(path)}:{line}  \\{name} already contains a percent sign')

    unused = sorted(defined - set(used))
    if unused:
        warnings.append('MACROS  defined but never used: ' + ', '.join('\\' + u for u in unused))

    # ---- 3. structure ------------------------------------------------------
    labels, refs, cites, bibitems, inputs = defaultdict(list), defaultdict(list), defaultdict(list), set(), defaultdict(list)
    for path, text in sources.items():
        for m in re.finditer(r'\\label\{([^}]+)\}', text):
            labels[m.group(1)].append(rel(path))
        for m in re.finditer(r'\\(?:eq)?ref\{([^}]+)\}', text):
            refs[m.group(1)].append(rel(path))
        for m in re.finditer(r'\\cite[tp]?\{([^}]+)\}', text):
            for k in m.group(1).split(','):
                cites[k.strip()].append(rel(path))
        for m in re.finditer(r'\\bibitem\{([^}]+)\}', text):
            bibitems.add(m.group(1))
        for m in re.finditer(r'\\input\{([^}]+)\}', text):
            inputs[m.group(1)].append(rel(path))

    for name, where in sorted(refs.items()):
        if name not in labels:
            problems.append(f'STRUCT  \\ref{{{name}}} in {where[0]} has no \\label')
    for name, where in sorted(labels.items()):
        if len(where) > 1:
            problems.append(f'STRUCT  duplicate \\label{{{name}}} in {", ".join(where)}')
    for key, where in sorted(cites.items()):
        if bibitems and key not in bibitems:
            problems.append(f'STRUCT  \\cite{{{key}}} in {where[0]} has no \\bibitem')
    orphan = sorted(bibitems - set(cites))
    if orphan:
        warnings.append('STRUCT  bibitems never cited: ' + ', '.join(orphan))

    for target, where in sorted(inputs.items()):
        cand = os.path.join(HERE, target if target.endswith('.tex') else target + '.tex')
        if not os.path.exists(cand):
            problems.append(f'STRUCT  \\input{{{target}}} in {where[0]} names a missing file')

    for path, text in sources.items():
        for env in ('table', 'figure'):
            for m in re.finditer(r'\\begin\{' + env + r'\}(.*?)\\end\{' + env + r'\}', text, re.DOTALL):
                body = m.group(1)
                line = text[:m.start()].count('\n') + 1
                if '\\caption' not in body:
                    problems.append(f'STRUCT  {rel(path)}:{line}  {env} without \\caption')
                if '\\label' not in body:
                    problems.append(f'STRUCT  {rel(path)}:{line}  {env} without \\label')
        for m in re.finditer(r'\\begin\{table\}(?:\[[^\]]*\])?(.*?)\\end\{table\}', text, re.DOTALL):
            if 'manifest' in m.group(1):
                line = text[:m.start()].count('\n') + 1
                problems.append(f'STRUCT  {rel(path)}:{line}  tables/manifest is a longtable and must not sit in a table float')

    # ---- environment balance ----------------------------------------------
    for path, text in sources.items():
        stack = []
        for m in re.finditer(r'\\(begin|end)\{([^}]+)\}', text):
            kind, env = m.group(1), m.group(2)
            line = text[:m.start()].count('\n') + 1
            if kind == 'begin':
                stack.append((env, line))
            else:
                if not stack:
                    problems.append(f'STRUCT  {rel(path)}:{line}  \\end{{{env}}} with no matching \\begin')
                elif stack[-1][0] != env:
                    problems.append(f'STRUCT  {rel(path)}:{line}  \\end{{{env}}} closes \\begin{{{stack[-1][0]}}} from line {stack[-1][1]}')
                    stack.pop()
                else:
                    stack.pop()
        for env, line in stack:
            problems.append(f'STRUCT  {rel(path)}:{line}  \\begin{{{env}}} is never closed')

    # ---- stray unicode -----------------------------------------------------
    SAFE = set('\n\t')
    for path, text in sources.items():
        for i, ch in enumerate(text):
            if ord(ch) > 127 and ch not in SAFE:
                line = text[:i].count('\n') + 1
                warnings.append(f'UNICODE {rel(path)}:{line}  U+{ord(ch):04X} {ch!r}')

    # ---- report ------------------------------------------------------------
    print(f'=== {profile.name} ({rel(profile.master)}) ===')
    for w in warnings:
        print('warn : ' + w)
    for p in problems:
        print('ERROR: ' + p)
    print(f'{len(problems)} problems, {len(warnings)} warnings, {len(sources)} files checked.\n')
    return len(problems)


def main(argv):
    wanted = [k for k in ('v04', 'v05') if '--' + k in argv]
    if not wanted:
        wanted = [k for k in ('v04', 'v05', 'v06') if PROFILES[k].present()]
    if not wanted:
        print('no manuscript found next to check.py')
        return 1
    total = 0
    for key in wanted:
        prof = PROFILES[key]
        if not prof.present():
            print(f'=== {prof.name} === not present; skipped\n')
            continue
        total += run(prof)
    return 1 if total else 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
