#!/usr/bin/env python3
"""Consistency sweep for the FishBot v0.4 manuscript.

Run from anywhere:  python3 paper/check.py

Three classes of check, all of which have caught real defects in this paper:

  1. BANNED  -- phrases the review of v0.4 ruled out, e.g. calling the
     declaration rule "optimal", calling the two-ply refinement "exact", or
     asserting an upper bound on exploitability.
  2. MACROS  -- every \\num... macro referenced by a section must be defined in
     numbers.tex (which is generated by engine/build_tables.py), and macros that
     already carry a percent sign must not be followed by another.
  3. STRUCTURE -- every \\ref/\\eqref resolves, every \\cite resolves, every
     \\input names a file that exists, and no table or figure lacks a caption or
     a label.

Exit status is non-zero if anything in class 1 or 2 fires, or if class 3 finds a
dangling reference.
"""
import os
import re
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
SECT = os.path.join(HERE, 'sections')

# ---------------------------------------------------------------- 1. banned
# (pattern, why).  Patterns are case-insensitive regexes matched against the
# LaTeX source with comments stripped.
BANNED = [
    (r'optimal[- ]stopping',            'the declaration rule is a value-based stopping rule, not an optimal-stopping solution'),
    (r'optimal stopping',               'same'),
    (r'\bexact two-ply\b',              'the two-ply branches are recomputed with the Sinkhorn approximation'),
    (r'two-ply.{0,40}\bexact\b',        'the two-ply branches are approximate'),
    (r'rules-exact',                    'say "exact for the specified rules dialect"'),
    (r'\bthe real rules\b',             'say "the rules dialect studied"'),
    (r'exact public[- ]belief',         'the posterior is observer-conditioned, not a common public belief'),
    (r'public belief state game',       'same'),
    (r'\bno previous (agent|work|engine)\b', 'use "we found no prior published work that ..."'),
    (r'\bthe first (Fish|agent|engine)\b',   'use "we found no prior published work that ..."'),
    (r'never been stated',              'use "we found no prior published work that ..."'),
    (r'upper bound.{0,40}exploitab',    'an achieved exploiter score is a lower bound within the search class'),
    (r'exploitab.{0,40}upper bound',    'same'),
    (r'prior .{0,20}adds nothing',      'removing the policy prior cost 3.88 points in the frozen-policy ablation'),
    (r'adds nothing once',              'same'),
    (r'rejection-free(?!.{0,80}C1)',    'rejection-free for C1-C4 only; C5 uses exact rejection'),
    (r'(safe|lossless) pre-?gate',      'the pre-gate has a measured non-zero false-negative rate (E16)'),
    (r'pre-?gate is (safe|lossless)',   'same'),
    (r'the honest (statement|summary|answer)', 'write the precise sentence instead'),
    (r'worth stating precisely',        'write the precise sentence instead'),
    (r'twenty times',                   'the Fast/Block throughput ratio is about 14x'),
    (r'31 (tuned |fitted )?(co-?ordinates|parameters)', 'the fitted vector has 34 coordinates'),
    (r'\$8 ?\\times ?8\$ policy',       'fish verify runs the 9x9 cross-product'),
    (r'four bounded claims',            'the contributions are a paragraph, not a numbered claim list'),
    (r'held-out opponents',             'deals were held out; most opponent identities were not'),
    (r'against \\emph\{every\} policy', 'scope the result to the tested panel'),
    (r'at least \\numWorstCase',        'scope the result to the tested panel'),
    (r'single most valuable',           'say "largest frozen-policy ablation decrease"'),
    (r'exactness makes.{0,30}worse',    'a Block belief substituted into a Fast-fitted policy scored lower'),
    (r'no more information can change', 'ownership may be fixed while allocation information still changes'),
    (r'validated against brute force(?!.{0,200}oracle)', 'cite the oracle experiment (E15) and its coverage'),
    (r'validated against exhaustive enumeration(?!.{0,140}(small|reachable|coverage))',
     'the oracle validates small reachable states only; say so'),
    (r'exhaustive enumeration(?!.{0,160}(small|reachable|skipped|coverage|partial))',
     'always scope the oracle to the states it actually enumerated'),
]

# Macros that already contain a percent sign; a following \% is a duplicate.
SELF_PERCENT = {'numLimitRate', 'numLBRLimit'}

# Several banned phrases are legitimate inside an explicit disclaimer -- the
# paper is required to say, for instance, that the rule is "not a Bellman-optimal
# stopping value".  A hit is suppressed when a negation cue appears close by.
NEGATION = re.compile(
    r'\b(?:not|never|no longer|rather than|instead of|does not|do not|is not|are not|'
    r'without|nor|neither|cannot|avoid|deny|denies|refrain|but not|other than|'
    r'we make no|makes no|no such|misleading|incorrect|wrong|must not)\b',
    re.IGNORECASE)
NEG_WINDOW = 220


def strip_comments(text):
    out = []
    for line in text.split('\n'):
        i, esc = 0, False
        cut = len(line)
        while i < len(line):
            c = line[i]
            if esc:
                esc = False
            elif c == '\\':
                esc = True
            elif c == '%':
                cut = i
                break
            i += 1
        out.append(line[:cut])
    return '\n'.join(out)


def tex_files():
    """Everything that ships: the sections, the generated tables and figures, and
    the master.  Tables are \\input from sections, so their content reaches the
    reader and has to be swept for banned phrasing and stray Unicode too."""
    files = []
    for d in (SECT, os.path.join(HERE, 'tables'), os.path.join(HERE, 'figures')):
        if not os.path.isdir(d):
            continue
        for name in sorted(os.listdir(d)):
            if name.endswith('.tex'):
                files.append(os.path.join(d, name))
    master = os.path.join(HERE, 'fishbot_v04.tex')
    if os.path.exists(master):
        files.append(master)
    return files


def main():
    problems, warnings = [], []

    sources = {}
    for path in tex_files():
        sources[path] = strip_comments(open(path, encoding='utf-8').read())

    rel = lambda p: os.path.relpath(p, HERE)

    # ---- 1. banned phrases -------------------------------------------------
    for path, text in sources.items():
        if rel(path).endswith('bibliography.tex'):
            continue
        for pat, why in BANNED:
            for m in re.finditer(pat, text, re.IGNORECASE | re.DOTALL):
                lo = max(0, m.start() - NEG_WINDOW)
                hi = min(len(text), m.end() + NEG_WINDOW)
                if NEGATION.search(text[lo:hi]):
                    line = text[:m.start()].count('\n') + 1
                    snippet = ' '.join(m.group(0).split())[:70]
                    warnings.append(f'BANNED? {rel(path)}:{line}  "{snippet}"  '
                                    f'-- appears near a negation; verify it is a disclaimer')
                    continue
                line = text[:m.start()].count('\n') + 1
                snippet = ' '.join(m.group(0).split())[:70]
                problems.append(f'BANNED  {rel(path)}:{line}  "{snippet}"  -- {why}')

    # ---- 2. macros ---------------------------------------------------------
    numbers = os.path.join(HERE, 'numbers.tex')
    defined = set()
    if os.path.exists(numbers):
        defined = set(re.findall(r'\\newcommand\{\\(num[A-Za-z]+)\}', open(numbers).read()))
    else:
        problems.append('MACROS  numbers.tex is missing; run engine/build_tables.py')

    used = defaultdict(list)
    for path, text in sources.items():
        for m in re.finditer(r'\\(num[A-Za-z]+)', text):
            used[m.group(1)].append((rel(path), text[:m.start()].count('\n') + 1))
    for name, sites in sorted(used.items()):
        if name not in defined:
            where = ', '.join(f'{f}:{l}' for f, l in sites[:3])
            problems.append(f'MACROS  \\{name} is used ({where}) but not defined in numbers.tex')

    for path, text in sources.items():
        for name in SELF_PERCENT:
            for m in re.finditer(r'\\' + name + r'(?![A-Za-z])\s*\\%', text):
                line = text[:m.start()].count('\n') + 1
                problems.append(f'MACROS  {rel(path)}:{line}  \\{name} already contains a percent sign')

    unused = sorted(defined - set(used))
    if unused:
        warnings.append('MACROS  defined but never used: ' + ', '.join('\\' + u for u in unused))

    # ---- 3. structure ------------------------------------------------------
    labels, refs, cites, bibitems, inputs = defaultdict(list), defaultdict(list), defaultdict(list), set(), defaultdict(list)
    for path, text in sources.items():
        for m in re.finditer(r'\\label\{([^}]+)\}', text):
            labels[m.group(1)].append(rel(path))
        for m in re.finditer(r'\\(?:eq)?ref\{([^}]+)\}', text):
            refs[m.group(1)].append(rel(path))
        for m in re.finditer(r'\\cite[tp]?\{([^}]+)\}', text):
            for k in m.group(1).split(','):
                cites[k.strip()].append(rel(path))
        for m in re.finditer(r'\\bibitem\{([^}]+)\}', text):
            bibitems.add(m.group(1))
        for m in re.finditer(r'\\input\{([^}]+)\}', text):
            inputs[m.group(1)].append(rel(path))

    for name, where in sorted(refs.items()):
        if name not in labels:
            problems.append(f'STRUCT  \\ref{{{name}}} in {where[0]} has no \\label')
    for name, where in sorted(labels.items()):
        if len(where) > 1:
            problems.append(f'STRUCT  duplicate \\label{{{name}}} in {", ".join(where)}')
    for key, where in sorted(cites.items()):
        if bibitems and key not in bibitems:
            problems.append(f'STRUCT  \\cite{{{key}}} in {where[0]} has no \\bibitem')
    orphan = sorted(bibitems - set(cites))
    if orphan:
        warnings.append('STRUCT  bibitems never cited: ' + ', '.join(orphan))

    for target, where in sorted(inputs.items()):
        cand = os.path.join(HERE, target if target.endswith('.tex') else target + '.tex')
        if not os.path.exists(cand):
            problems.append(f'STRUCT  \\input{{{target}}} in {where[0]} names a missing file')

    for path, text in sources.items():
        for env in ('table', 'figure'):
            for m in re.finditer(r'\\begin\{' + env + r'\}(.*?)\\end\{' + env + r'\}', text, re.DOTALL):
                body = m.group(1)
                line = text[:m.start()].count('\n') + 1
                if '\\caption' not in body:
                    problems.append(f'STRUCT  {rel(path)}:{line}  {env} without \\caption')
                if '\\label' not in body:
                    problems.append(f'STRUCT  {rel(path)}:{line}  {env} without \\label')
        for m in re.finditer(r'\\begin\{table\}(?:\[[^\]]*\])?(.*?)\\end\{table\}', text, re.DOTALL):
            if 'manifest' in m.group(1):
                line = text[:m.start()].count('\n') + 1
                problems.append(f'STRUCT  {rel(path)}:{line}  tables/manifest is a longtable and must not sit in a table float')

    # ---- environment balance ----------------------------------------------
    for path, text in sources.items():
        stack = []
        for m in re.finditer(r'\\(begin|end)\{([^}]+)\}', text):
            kind, env = m.group(1), m.group(2)
            line = text[:m.start()].count('\n') + 1
            if kind == 'begin':
                stack.append((env, line))
            else:
                if not stack:
                    problems.append(f'STRUCT  {rel(path)}:{line}  \\end{{{env}}} with no matching \\begin')
                elif stack[-1][0] != env:
                    problems.append(f'STRUCT  {rel(path)}:{line}  \\end{{{env}}} closes \\begin{{{stack[-1][0]}}} from line {stack[-1][1]}')
                    stack.pop()
                else:
                    stack.pop()
        for env, line in stack:
            problems.append(f'STRUCT  {rel(path)}:{line}  \\begin{{{env}}} is never closed')

    # ---- stray unicode -----------------------------------------------------
    SAFE = set('\n\t')
    for path, text in sources.items():
        for i, ch in enumerate(text):
            if ord(ch) > 127 and ch not in SAFE:
                line = text[:i].count('\n') + 1
                warnings.append(f'UNICODE {rel(path)}:{line}  U+{ord(ch):04X} {ch!r}')

    # ---- report ------------------------------------------------------------
    for w in warnings:
        print('warn : ' + w)
    for p in problems:
        print('ERROR: ' + p)
    print(f'\n{len(problems)} problems, {len(warnings)} warnings, {len(sources)} files checked.')
    return 1 if problems else 0


if __name__ == '__main__':
    sys.exit(main())
